<?php


namespace MP\Base\Http\Filters\Types;


use Illuminate\Support\Facades\DB;

class NameFilter extends FilterType
{
    public function filter($builder, $filter)
    {
        return parent::filter($builder, $filter); // TODO: Change the autogenerated stub
    }
}
